---
title: "Estudio datos 2022"
author: "Gema Bravo, Josep Peiro, Candela Santandreu, Mireia Risueño & Javier Montaner"
date: "16/4/2022"
output: html_document
---

```{r setup, cache = F, echo = F, message = F, warning = F, tidy = F}

# CONFIGURACIÓN GENERAL
library(knitr)
options(width = 100)

# Opciones generales de los chucks. Se utilizarán salvo cambios en el chunk
opts_chunk$set(echo=T, message = F, error = F, warning = F, comment = NA, fig.align = 'center', dpi = 200, tidy = F, cache.path = '.cache/', fig.path = './figura/')

# Opciones generales de dígitos cuando se incluyen tablas
#options(xtable.type = 'html')
knit_hooks$set(inline = function(x) {
  
  if(is.numeric(x)) {
    round(x, getOption('digits'))
  } else {
    paste(as.character(x), collapse = ', ')
  }
})
#knit_hooks$set(plot = knitr:::hook_plot_html)
```

```{r, echo=F}
# Especificamos las librerías necesarias en esta lista

packages = c("readr","dplyr","lubridate", "tidyr","tibble", "ggplot2", "purrr")

#use this function to check if each package is on the local machine
#if a package is installed, it will be loaded
#if any are not, the missing package(s) will be installed and loaded
package.check <- lapply(packages, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE,repos='http://cran.rediris.es')
  }
  library(x, character.only = TRUE)
})

#verify they are loaded
#search()

```

Este sera el Rmd donde trabajaremos con los datos de 2022

## Carga de datos
```{r}
load("./dataframes/datos_2022.Rdata")
```

## Estudio estadistico
```{r}
estadisticos = function(x){
  minimo = round(min(x, na.rm=T),2)
  percentil_25 = round(quantile(x, 0.25, na.rm=T),2)
  mediana = round(median(x, na.rm=T),2)
  media = round(mean(x, na.rm=T),2)
  desviacion_tipica = round(sd(x, na.rm=T),2)
  percentil_75 = round(quantile(x, 0.75, na.rm=T),2)
  maximo = round(max(x, na.rm=T),2)
  vector = c(minimo, percentil_25, mediana, media, desviacion_tipica, percentil_75, maximo)
  names(vector)=NULL
  return (vector)
}
```

```{r}
tabla_estadisticos = data.frame()

for (a in datos_2022[,2:6]){
  b = estadisticos(a)
  tabla_estadisticos=rbind(tabla_estadisticos, b)
}

colnames(tabla_estadisticos) = c("minimo", "percentil_25", "mediana", "media", "desviacion_tipica", "percentil_75", "maximo")
rownames(tabla_estadisticos)=colnames(datos_2022[,2:6])
tabla_estadisticos
```

```{r}
datos_2022 = datos_2022 %>% select(-year) %>% gather("noise", "value", 2:6)
```

```{r}
ggplot(datos_2022, aes(noise, value))+geom_boxplot()
```
##Preguntas
-¿Ha incrementado el ruido en los últimos 3 años?
